version: "3.9"
services:
  db:
    container_name: mysql-spring-api
    image: "mysql"
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: spring-rest-api
    volumes:
      - "./mysqldata:/var/lib/mysql"

volumes:
  mysqldata: